 #set( $dollar = '$' )

server:
  port: ${swagger-catalog-port}
documentation: 
  baseurl: http://localhost
  swagger: 
    services:   
      - 
        name: Personas
        url: ${dollar}{documentation.baseurl}:52037/api/v2/api-docs?group=Personas
        version: 1.0
#      - 
#        name: Service2
#        url: ${dollar}{documentation.baseurl}:8050/v2/api-docs?group=service2
#        version: 2.0
# 
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://${eureka-host}:${eureka-port}/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
spring.sleuth.sampler.percentage: 1.0
spring.sleuth.web.skipPattern: (^cleanup.*)          