spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/rafabc/microservices-maven-archetypes
          skipSslValidation: true
          default-label: master
          search-paths: archetype-config-server,config* #/src/main/resources/archetype-resources/src/main/resources/config
  profiles:
     active: native


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: ${dollar}{URL_EUREKA:http:///${eureka-host}:${eureka-port}/eureka}
      #defaultZone: http://${eureka-host}:${eureka-port}/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5 