spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/rafabc/microservice-graphql
          default-label: master
          search-paths: microservice_config_server/src/main/resources/config
  profiles:
     active: native


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://${eureka-host}:${eureka-port}/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5  