sudo: true
language: java
jdk:
- oraclejdk8

#install: "./mvn-install-archetypes.sh"
#script: "./mvn-create-samples.sh"


#before_install:
#  - chmod +x mvn-install-archetypes.sh
#  - chmod +x mvn-create-samples.sh
#  - chmod +x ./deploy.sh


#before_deploy:
#  - chmod +x ./deploy.sh


#deploy:
#  provider: elasticbeanstalk
#  access_key_id: "secret"
#  secret_access_key: "YOUR AWS SECRET KEY"
#  bucket: "S3 Bucket"
#  key: latest/MyApp.zip
#  application: MyApp
#  deployment_group: MyDeploymentGroup

deploy:
  provider: elasticbeanstalk
  access_key_id: ${aws_access_key_id}
  secret_access_key:
    secure: ${aws_secret_acces_key}
  region: "us-east-2"  
  app: "microservices"
  env: "microservices-env"
  bucket_name: "elasticbeanstalk-us-east-2-532222486980"  

#deploy:
#  provider: heroku
#  app: micro-config-server
#  skip_cleanup: true
#  api_key:
#    secure: 8af7a514-9b3c-4e51-acb5-dbb11d329506
