 #set( $dollar = '$' )
server:
    port: ${eureka-port}
   
eureka:
  instance:
    hostname: ${eureka-host}
    prefer-ip-address: true
    
    statusPageUrlPath: ${dollar}{management.contextPath}/info
    healthCheckUrlPath: ${dollar}{management.contextPath}/health
    metadataMap:
      instanceId: ${dollar}{vcap.application.instance_id:${dollar}{spring.application.name}:${dollar}{spring.application.instance_id:${dollar}{server.port}}}
  client:
    serviceUrl:
      defaultZone: http://${eureka-host}:${eureka-port}/eureka/   #necesary to eureka dont try to config peer zone in 8761 por by default
    registerWithEureka: true
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0  
    enableSelfPreservation: true
    
eureka.server.renewalPercentThreshold: 10
eureka.instance.leaseRenewalIntervalInSeconds: 5      
    
    

#spring.boot.admin.url: http://localhost:3333               