
server:
  port: ${spring-boot-admin-port}
    
eureka:
  instance:
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://${eureka-host}:${eureka-port}/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5 