#set( $dollar = '$' ) 

eureka:
  instance:
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: ${dollar}{URL_EUREKA:http:///${eureka-host}:${eureka-port}/eureka}
    healthcheck:
      enabled: true
    lease:
      duration: 5     