server:
  port: ${zipkin-port}
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://${eureka-host}:${eureka-port}/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
      
management.security.enabled: false #disabled for get acces to logging info from spring boot admin