server:
  port: ${zuul-port}
management:
  port: 9094
  ssl:
    enabled: false
zuul:
  routes:
    example-service:
      #path: /service/**
      #serviceId: serviceid
 
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://${eureka-host}:${eureka-port}/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5 
      
spring.sleuth.sampler.percentage: 1.0
spring.sleuth.web.skipPattern: (^cleanup.*)          